version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "8080:8080"
    restart: unless-stopped

  client:
    build: ./client
    ports:
      - "5173:5173"
    restart: unless-stopped
